// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LaboratorioWebApi.Data.Entities;

public partial class Barrios
{
    public int CodBarrio { get; set; }

    public string Barrio { get; set; }

    public int? CodCiudad { get; set; }

    public virtual Ciudades CodCiudadNavigation { get; set; }

    public virtual ICollection<Pacientes> Pacientes { get; set; } = new List<Pacientes>();
}