// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace LaboratorioWebApi.Data.Entities;

[Table("DETALLES_MUESTRAS")]
public class DetallesMuestras
{
    [Column("ID_DETALLES_MUESTRAS")]
    public int IdDetallesMuestras { get; set; }
    [Column("id_muestra")]
    public int IdMuestra { get; set; }
    [Column("cod_nbu")]
    public int CodNbu { get; set; }
    [Column("id_tipo_estado")]
    public int IdTipoEstado { get; set; }
    [JsonIgnore]
    public string Detalle { get; set; }
    [JsonIgnore]
    public virtual Practicas CodNbuNavigation { get; set; }
    [JsonIgnore]
    public virtual Muestras IdMuestraNavigation { get; set; }
    [JsonIgnore]
    public virtual TiposEstados IdTipoEstadoNavigation { get; set; }

    //public virtual Practicas PRACTICAS { get; set; }
    //public virtual LabDerivaciones lab_derivaciones { get; set; }
    //public virtual Muestras MUESTRAS { get; set; }
    //public virtual TiposEstados TIPOS_Estados { get; set; }
}