// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LaboratorioWebApi.Data.Entities;

public partial class DetallesFactura
{
    public int IdDetalleFact { get; set; }

    public int? NroFactura { get; set; }

    public int? CodNbu { get; set; }

    public int? Cantidad { get; set; }

    public decimal? Precio { get; set; }

    public virtual Practicas CodNbuNavigation { get; set; }

    public virtual Facturas NroFacturaNavigation { get; set; }
}