// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LaboratorioWebApi.Data.Entities;

public partial class LabDerivaciones
{
    public int DerivadaA { get; set; }

    public string NombreLaboratorioDerivado { get; set; }

    public bool EsActivo { get; set; }

    public int CodCiudad { get; set; }

    public virtual Ciudades CodCiudadNavigation { get; set; }

    public virtual ICollection<Practicas> Practicas { get; set; } = new List<Practicas>();

    public virtual ICollection<PracticasLabDerivaciones> PracticasLabDerivaciones { get; set; } = new List<PracticasLabDerivaciones>();
}