// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using LaboratorioWebApi.Data.Extensions;
using LaboratorioWebApi.Data.Procedures;
using LaboratorioWebApi.Data.Repositories;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace LaboratorioWebApi.Data.Entities
{
    public partial class LaboratorioDbContext
    {
        private ILaboratorioDbContextProceduresRepository _procedures;

        public virtual ILaboratorioDbContextProceduresRepository Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new LaboratorioDbContextProceduresRepository(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IEnumerable<object> DETALLES_MUESTRAS { get; internal set; }

        public ILaboratorioDbContextProceduresRepository GetProcedures()
        {
            return Procedures;
        }
    }

}
