// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LaboratorioWebApi.Data.Entities;

public partial class PracticasLabDerivaciones
{
    public int CodPracLabDeriv { get; set; }

    public int CodNbu { get; set; }

    public int DerivadaA { get; set; }

    public decimal PrecioDeriv { get; set; }

    public int DiasDemora { get; set; }

    public virtual Practicas CodNbuNavigation { get; set; }

    public virtual LabDerivaciones DerivadaANavigation { get; set; }
}