// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace LaboratorioWebApi.Data.Entities;

public partial class Practicas
{
    [Column("cod_nbu")]
    public int CodNbu { get; set; }

    public string NomPractica { get; set; }

    public int? DerivadaA { get; set; }

    public bool EsActiva { get; set; }

    public int CantUb { get; set; }

    public int? IdTipoMuestra { get; set; }

    public virtual ICollection<ConveniosPracticas> ConveniosPracticas { get; set; } = new List<ConveniosPracticas>();

    public virtual LabDerivaciones DerivadaANavigation { get; set; }

    public virtual ICollection<DetallesFactura> DetallesFacturas { get; set; } = new List<DetallesFactura>();

    public virtual ICollection<DetallesMuestras> DetallesMuestras { get; set; } = new List<DetallesMuestras>();

    public virtual TiposMuestras IdTipoMuestraNavigation { get; set; }

    public virtual ICollection<PracticasLabDerivaciones> PracticasLabDerivaciones { get; set; } = new List<PracticasLabDerivaciones>();
}