// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LaboratorioWebApi.Data.Entities;

public partial class TiposDocumentos
{
    public int IdTipoDocumento { get; set; }

    public string Detalle { get; set; }

    public virtual ICollection<Pacientes> Pacientes { get; set; } = new List<Pacientes>();
}