// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LaboratorioWebApi.Data.Entities;

public partial class TiposMuestras
{
    public int IdTipoMuestra { get; set; }

    public string TipoMuestra { get; set; }

    public virtual ICollection<Practicas> Practicas { get; set; } = new List<Practicas>();
}