// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LaboratorioWebApi.Data.Entities;

public partial class TiposEstados
{
    public int IdTipoEstado { get; set; }

    public string Estado { get; set; }

    public virtual ICollection<DetallesMuestras> DetallesMuestras { get; set; } = new List<DetallesMuestras>();

    public virtual ICollection<Muestras> Muestras { get; set; } = new List<Muestras>();
}