// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using LaboratorioWebApi.Data.Extensions;
using LaboratorioWebApi.Data.Procedures;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace LaboratorioWebApi.Data.Repositories
{
    public partial interface ILaboratorioDbContextProceduresRepository
    {
        Task<List<sp_costo_deriv_por_laboratorioResult>> sp_costo_deriv_por_laboratorioAsync
            (DateTime? fechaDesde, DateTime? fechaHasta, OutputParameter<int> 
            returnValue = null, CancellationToken cancellationToken = default);

        Task<List<sp_costo_total_derivacionesResult>> sp_costo_total_derivacionesAsync
            (DateTime? fechaDesde, DateTime? fechaHasta, OutputParameter<int> 
            returnValue = null, CancellationToken cancellationToken = default);

        Task<List<sp_estado_muestrasResult>> sp_estado_muestrasAsync
            (string estado, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);

        Task<List<sp_muestras_para_informarResult>> sp_muestras_para_informarAsync
            (OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);

        Task<List<sp_practicas_fuera_coberturaResult>> GetPracticasFueraCoberturaAsync();
    }
}
